/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View_Layer;

/**
 *
 * @author sachithra
 */
public class MedicineSearch extends javax.swing.JDialog {

    /**
     * Creates new form search
     */
    public MedicineSearch(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_Barcode_Number = new javax.swing.JLabel();
        lbl_Medicine_Name = new javax.swing.JLabel();
        lbl_Brand_Name = new javax.swing.JLabel();
        txt_Barcode_Number = new javax.swing.JTextField();
        txt_Medicine_Name = new javax.swing.JTextField();
        txt_Brand_Name = new javax.swing.JTextField();
        btn_Submit = new javax.swing.JButton();
        btn_Back = new javax.swing.JButton();
        checkBox_Barcode_Number = new javax.swing.JCheckBox();
        checkBox_Medicine_Name = new javax.swing.JCheckBox();
        checkBox_Brand_Name = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbl_Barcode_Number.setText("Barcode Number");

        lbl_Medicine_Name.setText("Medicine Name");

        lbl_Brand_Name.setText("Brand Name");

        txt_Barcode_Number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Barcode_NumberActionPerformed(evt);
            }
        });

        txt_Medicine_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Medicine_NameActionPerformed(evt);
            }
        });

        txt_Brand_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Brand_NameActionPerformed(evt);
            }
        });

        btn_Submit.setText("Submit");
        btn_Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SubmitActionPerformed(evt);
            }
        });

        btn_Back.setText("Back");
        btn_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BackActionPerformed(evt);
            }
        });

        checkBox_Barcode_Number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox_Barcode_NumberActionPerformed(evt);
            }
        });

        checkBox_Medicine_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox_Medicine_NameActionPerformed(evt);
            }
        });

        checkBox_Brand_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox_Brand_NameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(checkBox_Barcode_Number)
                    .addComponent(checkBox_Medicine_Name)
                    .addComponent(checkBox_Brand_Name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_Barcode_Number)
                    .addComponent(lbl_Medicine_Name, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Brand_Name, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_Medicine_Name, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_Barcode_Number, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_Brand_Name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(251, Short.MAX_VALUE)
                .addComponent(btn_Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Barcode_Number)
                    .addComponent(txt_Barcode_Number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkBox_Barcode_Number))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Medicine_Name)
                    .addComponent(txt_Medicine_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkBox_Medicine_Name))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Brand_Name)
                    .addComponent(txt_Brand_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkBox_Brand_Name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Back)
                    .addComponent(btn_Submit))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SubmitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_SubmitActionPerformed

    private void btn_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_BackActionPerformed

    private void txt_Barcode_NumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Barcode_NumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Barcode_NumberActionPerformed

    private void txt_Medicine_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Medicine_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Medicine_NameActionPerformed

    private void txt_Brand_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Brand_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Brand_NameActionPerformed

    private void checkBox_Barcode_NumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox_Barcode_NumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBox_Barcode_NumberActionPerformed

    private void checkBox_Medicine_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox_Medicine_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBox_Medicine_NameActionPerformed

    private void checkBox_Brand_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox_Brand_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBox_Brand_NameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedicineSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedicineSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedicineSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedicineSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MedicineSearch dialog = new MedicineSearch(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Back;
    private javax.swing.JButton btn_Submit;
    private javax.swing.JCheckBox checkBox_Barcode_Number;
    private javax.swing.JCheckBox checkBox_Brand_Name;
    private javax.swing.JCheckBox checkBox_Medicine_Name;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_Barcode_Number;
    private javax.swing.JLabel lbl_Brand_Name;
    private javax.swing.JLabel lbl_Medicine_Name;
    private javax.swing.JTextField txt_Barcode_Number;
    private javax.swing.JTextField txt_Brand_Name;
    private javax.swing.JTextField txt_Medicine_Name;
    // End of variables declaration//GEN-END:variables
}
