/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View_Layer;

import Business_Logic_Layer.Patient;
import HealthCareCenter.PatientLogic;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class PatientOptionForm extends javax.swing.JFrame {

    /**
     * Creates new form PatientOptionForm
     */
    public PatientOptionForm() throws SQLException {
        initComponents();
        DefaultComboBoxModel  nameModel = new DefaultComboBoxModel( myLogicLayer.getNames());
       this.Diagnose_Combobox_Name.setModel(nameModel);
       arrayIndex=0;
    }
    
     String name;
    String age;
    String gender;
    String familyName;
    String contactNo;
    
    PatientLogic myLogicLayer=new PatientLogic();
    //String name;
    String history;
    String prescription;
    double sugarLevel;
    double pressureLevel;
    String medicineArray[]=new String[10];
    String quantityArray[]=new String[10];
    int arrayIndex=0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        InsertPanel = new javax.swing.JPanel();
        Insert_lbl_Age = new javax.swing.JLabel();
        Insert_textfield_Age = new javax.swing.JTextField();
        Insert_lbl_Gender = new javax.swing.JLabel();
        Insert_radioButton_male = new javax.swing.JRadioButton();
        Insert_radioButton_female = new javax.swing.JRadioButton();
        Insert_lbl_ContactNo = new javax.swing.JLabel();
        Insert_textfield_gender = new javax.swing.JTextField();
        Insert_lbl_FamilyName = new javax.swing.JLabel();
        Insert_textfield_familyname = new javax.swing.JTextField();
        Insert_lbl_Name = new javax.swing.JLabel();
        InsertButton = new javax.swing.JButton();
        Insert_textfield_Name = new javax.swing.JTextField();
        ViewPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        View_table = new javax.swing.JTable();
        View_Button_Load = new javax.swing.JButton();
        PatientHistoryPanel = new javax.swing.JPanel();
        FamilyHistoryPanel = new javax.swing.JPanel();
        DiagnosePanel = new javax.swing.JPanel();
        Diagnose_lbl_SelectQuantity = new javax.swing.JLabel();
        Diagnose_textfield_Dose = new javax.swing.JTextField();
        Diagnose_Button_OK = new javax.swing.JButton();
        Diagnose_lbl_Name = new javax.swing.JLabel();
        Diagnose_Button_Cancel = new javax.swing.JButton();
        Diagnose_lbl_PatientHistory = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Diagnose_Textarea_PreviousHistory = new javax.swing.JTextArea();
        Diagnose_lbl_Prescription = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        Diagnose_List_Quantity = new javax.swing.JList();
        Diagnose_lbl_SugarLevel = new javax.swing.JLabel();
        Diagnose_lbl_Mdicine = new javax.swing.JLabel();
        Diagnose_lbl_PressureLevel = new javax.swing.JLabel();
        Diagnose_lbl_Quantity = new javax.swing.JLabel();
        Diagnose_textfield_sugarLevel = new javax.swing.JTextField();
        Diagnose_lbl_Tablets = new javax.swing.JLabel();
        Diagnose_textfield_pressureLevel = new javax.swing.JTextField();
        Diagnose_lbl_Bottles = new javax.swing.JLabel();
        Diagnose_lbl_PreviousPrescription = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Diagnose_textarea_prescription = new javax.swing.JTextArea();
        Diagnose_textfield_DoseperDay = new javax.swing.JTextField();
        Diagnose_Combobox_Medicine = new javax.swing.JComboBox();
        Diagnose_lbl_SelectMedicine = new javax.swing.JLabel();
        Diagnose_Button_Add = new javax.swing.JButton();
        Diagnose_textarea_Remarks = new javax.swing.JTextField();
        Diagnose_lbl_Remarks = new javax.swing.JLabel();
        Diagnose_Combobox_Name = new javax.swing.JComboBox();
        jScrollPane4 = new javax.swing.JScrollPane();
        Diagnose_List_Medicine = new javax.swing.JList();
        Diagnose_textfield_Days = new javax.swing.JTextField();
        Diagnose_lbl_Days = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Diagnose_textfield_Volume = new javax.swing.JTextField();

        Insert_lbl_Age.setText("Age");

        Insert_textfield_Age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Insert_textfield_AgeActionPerformed(evt);
            }
        });

        Insert_lbl_Gender.setText("Gender");

        Insert_radioButton_male.setText("Male");
        Insert_radioButton_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Insert_radioButton_maleActionPerformed(evt);
            }
        });

        Insert_radioButton_female.setText("Female");
        Insert_radioButton_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Insert_radioButton_femaleActionPerformed(evt);
            }
        });

        Insert_lbl_ContactNo.setText("Contact No.");

        Insert_textfield_gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Insert_textfield_genderActionPerformed(evt);
            }
        });

        Insert_lbl_FamilyName.setText("Family Name");

        Insert_textfield_familyname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Insert_textfield_familynameActionPerformed(evt);
            }
        });

        Insert_lbl_Name.setText("Name");

        InsertButton.setText("Insert");
        InsertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertButtonActionPerformed(evt);
            }
        });

        Insert_textfield_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Insert_textfield_NameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InsertPanelLayout = new javax.swing.GroupLayout(InsertPanel);
        InsertPanel.setLayout(InsertPanelLayout);
        InsertPanelLayout.setHorizontalGroup(
            InsertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsertPanelLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(InsertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Insert_lbl_Name)
                    .addComponent(Insert_lbl_Age)
                    .addComponent(Insert_lbl_Gender)
                    .addComponent(Insert_lbl_ContactNo)
                    .addComponent(Insert_lbl_FamilyName))
                .addGap(92, 92, 92)
                .addGroup(InsertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Insert_radioButton_female)
                    .addComponent(Insert_radioButton_male)
                    .addComponent(Insert_textfield_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Insert_textfield_familyname, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Insert_textfield_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Insert_textfield_Age, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(245, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InsertPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(InsertButton)
                .addGap(82, 82, 82))
        );
        InsertPanelLayout.setVerticalGroup(
            InsertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsertPanelLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(InsertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Insert_lbl_Name)
                    .addComponent(Insert_textfield_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(InsertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Insert_lbl_Age)
                    .addComponent(Insert_textfield_Age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(InsertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Insert_lbl_Gender)
                    .addComponent(Insert_radioButton_male))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Insert_radioButton_female)
                .addGroup(InsertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InsertPanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(Insert_lbl_ContactNo))
                    .addGroup(InsertPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Insert_textfield_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(InsertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Insert_lbl_FamilyName)
                    .addComponent(Insert_textfield_familyname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(InsertButton)
                .addContainerGap(296, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Insert a new Patient", InsertPanel);

        View_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Age", "NIC", "Gender", "Family Name", "Contact No."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(View_table);

        View_Button_Load.setText("Load");
        View_Button_Load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_Button_LoadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ViewPanelLayout = new javax.swing.GroupLayout(ViewPanel);
        ViewPanel.setLayout(ViewPanelLayout);
        ViewPanelLayout.setHorizontalGroup(
            ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewPanelLayout.createSequentialGroup()
                .addContainerGap(722, Short.MAX_VALUE)
                .addComponent(View_Button_Load)
                .addGap(44, 44, 44))
            .addGroup(ViewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        ViewPanelLayout.setVerticalGroup(
            ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
                .addGap(32, 32, 32)
                .addComponent(View_Button_Load)
                .addGap(21, 21, 21))
        );

        jTabbedPane1.addTab("View Patient details", ViewPanel);

        javax.swing.GroupLayout PatientHistoryPanelLayout = new javax.swing.GroupLayout(PatientHistoryPanel);
        PatientHistoryPanel.setLayout(PatientHistoryPanelLayout);
        PatientHistoryPanelLayout.setHorizontalGroup(
            PatientHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 821, Short.MAX_VALUE)
        );
        PatientHistoryPanelLayout.setVerticalGroup(
            PatientHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Browse Patient History", PatientHistoryPanel);

        javax.swing.GroupLayout FamilyHistoryPanelLayout = new javax.swing.GroupLayout(FamilyHistoryPanel);
        FamilyHistoryPanel.setLayout(FamilyHistoryPanelLayout);
        FamilyHistoryPanelLayout.setHorizontalGroup(
            FamilyHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 821, Short.MAX_VALUE)
        );
        FamilyHistoryPanelLayout.setVerticalGroup(
            FamilyHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Browse Family History", FamilyHistoryPanel);

        Diagnose_lbl_SelectQuantity.setText("Select Quantity");

        Diagnose_textfield_Dose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Diagnose_textfield_DoseActionPerformed(evt);
            }
        });

        Diagnose_Button_OK.setText("OK");
        Diagnose_Button_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Diagnose_Button_OKActionPerformed(evt);
            }
        });

        Diagnose_lbl_Name.setText("Name");

        Diagnose_Button_Cancel.setText("Cancel");

        Diagnose_lbl_PatientHistory.setText("Patient History");

        Diagnose_Textarea_PreviousHistory.setColumns(20);
        Diagnose_Textarea_PreviousHistory.setRows(5);
        jScrollPane2.setViewportView(Diagnose_Textarea_PreviousHistory);

        Diagnose_lbl_Prescription.setText("Prescription");

        jScrollPane5.setViewportView(Diagnose_List_Quantity);

        Diagnose_lbl_SugarLevel.setText("Patient Blood Suger Level");

        Diagnose_lbl_Mdicine.setText("Medicine");

        Diagnose_lbl_PressureLevel.setText("Patient Blood Pressure Level");

        Diagnose_lbl_Quantity.setText("Quantity");

        Diagnose_textfield_sugarLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Diagnose_textfield_sugarLevelActionPerformed(evt);
            }
        });

        Diagnose_lbl_Tablets.setText("Dose  ");

        Diagnose_textfield_pressureLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Diagnose_textfield_pressureLevelActionPerformed(evt);
            }
        });

        Diagnose_lbl_Bottles.setText("Doses per Day");

        Diagnose_lbl_PreviousPrescription.setText("Previous Prescription  ");

        Diagnose_textarea_prescription.setColumns(20);
        Diagnose_textarea_prescription.setRows(5);
        jScrollPane3.setViewportView(Diagnose_textarea_prescription);

        Diagnose_textfield_DoseperDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Diagnose_textfield_DoseperDayActionPerformed(evt);
            }
        });

        Diagnose_Combobox_Medicine.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "pandol", "vitamin C", "piriton", "disprin", "corex - D" }));
        Diagnose_Combobox_Medicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Diagnose_Combobox_MedicineActionPerformed(evt);
            }
        });

        Diagnose_lbl_SelectMedicine.setText("Select Medicine");

        Diagnose_Button_Add.setText("Add");
        Diagnose_Button_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Diagnose_Button_AddActionPerformed(evt);
            }
        });

        Diagnose_textarea_Remarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Diagnose_textarea_RemarksActionPerformed(evt);
            }
        });

        Diagnose_lbl_Remarks.setText("Special Remarks");

        Diagnose_Combobox_Name.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Diagnose_Combobox_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Diagnose_Combobox_NameActionPerformed(evt);
            }
        });

        Diagnose_List_Medicine.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                Diagnose_List_MedicineValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(Diagnose_List_Medicine);

        Diagnose_textfield_Days.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Diagnose_textfield_DaysActionPerformed(evt);
            }
        });

        Diagnose_lbl_Days.setText("Days");

        jLabel2.setText("Volume");

        Diagnose_textfield_Volume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Diagnose_textfield_VolumeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DiagnosePanelLayout = new javax.swing.GroupLayout(DiagnosePanel);
        DiagnosePanel.setLayout(DiagnosePanelLayout);
        DiagnosePanelLayout.setHorizontalGroup(
            DiagnosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DiagnosePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(DiagnosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DiagnosePanelLayout.createSequentialGroup()
                        .addGroup(DiagnosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DiagnosePanelLayout.createSequentialGroup()
                                .addGroup(DiagnosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Diagnose_lbl_PatientHistory)
                                    .addComponent(Diagnose_lbl_SelectMedicine))
                                .addGap(39, 39, 39)
                                .addGroup(DiagnosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Diagnose_lbl_PressureLevel)
                                    .addComponent(Diagnose_lbl_Remarks)
                                    .addGroup(DiagnosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Diagnose_textfield_pressureLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(DiagnosePanelLayout.createSequentialGroup()
                                            .addComponent(Diagnose_lbl_SugarLevel)
                                            .addGap(43, 43, 43)
                                            .addComponent(Diagnose_textfield_sugarLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(Diagnose_Combobox_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Diagnose_textarea_Remarks, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(DiagnosePanelLayout.createSequentialGroup()
                                        .addComponent(Diagnose_Combobox_Medicine, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(89, 89, 89)
                                        .addComponent(Diagnose_lbl_SelectQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(DiagnosePanelLayout.createSequentialGroup()
                                .addComponent(Diagnose_lbl_PreviousPrescription)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Diagnose_lbl_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(85, 85, 85)
                        .addGroup(DiagnosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DiagnosePanelLayout.createSequentialGroup()
                                .addGap(0, 45, Short.MAX_VALUE)
                                .addGroup(DiagnosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DiagnosePanelLayout.createSequentialGroup()
                                        .addComponent(Diagnose_lbl_Mdicine)
                                        .addGap(186, 186, 186))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DiagnosePanelLayout.createSequentialGroup()
                                        .addComponent(Diagnose_lbl_Prescription)
                                        .addGap(111, 111, 111))))
                            .addGroup(DiagnosePanelLayout.createSequentialGroup()
                                .addGroup(DiagnosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(DiagnosePanelLayout.createSequentialGroup()
                                        .addComponent(Diagnose_Button_OK)
                                        .addGap(18, 18, 18)
                                        .addComponent(Diagnose_Button_Cancel))
                                    .addGroup(DiagnosePanelLayout.createSequentialGroup()
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addGroup(DiagnosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Diagnose_lbl_Quantity)
                                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DiagnosePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(DiagnosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DiagnosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DiagnosePanelLayout.createSequentialGroup()
                                    .addGroup(DiagnosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Diagnose_lbl_Tablets)
                                        .addComponent(Diagnose_lbl_Bottles))
                                    .addGap(77, 77, 77))
                                .addGroup(DiagnosePanelLayout.createSequentialGroup()
                                    .addComponent(Diagnose_lbl_Days)
                                    .addGap(123, 123, 123)))
                            .addGroup(DiagnosePanelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(113, 113, 113)))
                        .addGroup(DiagnosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Diagnose_textfield_Volume, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addGroup(DiagnosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Diagnose_textfield_Days)
                                .addComponent(Diagnose_textfield_Dose, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                .addComponent(Diagnose_textfield_DoseperDay)))
                        .addGap(110, 110, 110)
                        .addComponent(Diagnose_Button_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))))
        );
        DiagnosePanelLayout.setVerticalGroup(
            DiagnosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DiagnosePanelLayout.createSequentialGroup()
                .addGroup(DiagnosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DiagnosePanelLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(Diagnose_lbl_Prescription)
                        .addGap(18, 18, 18)
                        .addGroup(DiagnosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Diagnose_lbl_Mdicine)
                            .addComponent(Diagnose_lbl_Quantity)))
                    .addGroup(DiagnosePanelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(DiagnosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Diagnose_lbl_Name)
                            .addComponent(Diagnose_Combobox_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(DiagnosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Diagnose_lbl_PatientHistory)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(12, 12, 12)
                .addGroup(DiagnosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DiagnosePanelLayout.createSequentialGroup()
                        .addGroup(DiagnosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Diagnose_lbl_PreviousPrescription)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(DiagnosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Diagnose_lbl_SugarLevel)
                            .addComponent(Diagnose_textfield_sugarLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DiagnosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Diagnose_lbl_PressureLevel)
                            .addComponent(Diagnose_textfield_pressureLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(DiagnosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Diagnose_Combobox_Medicine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Diagnose_lbl_SelectMedicine)
                            .addComponent(Diagnose_lbl_SelectQuantity)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DiagnosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Diagnose_textfield_Dose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Diagnose_lbl_Tablets))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DiagnosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Diagnose_lbl_Bottles)
                    .addComponent(Diagnose_textfield_DoseperDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DiagnosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Diagnose_textfield_Days, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Diagnose_lbl_Days))
                .addGap(18, 18, 18)
                .addGroup(DiagnosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Diagnose_textfield_Volume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Diagnose_Button_Add))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Diagnose_lbl_Remarks)
                .addGap(18, 18, 18)
                .addGroup(DiagnosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DiagnosePanelLayout.createSequentialGroup()
                        .addGroup(DiagnosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Diagnose_Button_OK)
                            .addComponent(Diagnose_Button_Cancel))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DiagnosePanelLayout.createSequentialGroup()
                        .addComponent(Diagnose_textarea_Remarks, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jTabbedPane1.addTab("Diagnose Patient", DiagnosePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Insert_textfield_AgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Insert_textfield_AgeActionPerformed
        // TODO add your handling code here:
        age= evt.getActionCommand();
    }//GEN-LAST:event_Insert_textfield_AgeActionPerformed

    private void Insert_radioButton_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Insert_radioButton_maleActionPerformed
        // TODO add your handling code here:
        gender="male";
    }//GEN-LAST:event_Insert_radioButton_maleActionPerformed

    private void Insert_radioButton_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Insert_radioButton_femaleActionPerformed
        // TODO add your handling code here:
        gender="female";
    }//GEN-LAST:event_Insert_radioButton_femaleActionPerformed

    private void Insert_textfield_genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Insert_textfield_genderActionPerformed
        // TODO add your handling code here:
        contactNo=evt.getActionCommand();
    }//GEN-LAST:event_Insert_textfield_genderActionPerformed

    private void Insert_textfield_familynameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Insert_textfield_familynameActionPerformed
        // TODO add your handling code here:
        familyName=evt.getActionCommand();
    }//GEN-LAST:event_Insert_textfield_familynameActionPerformed

    private void InsertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertButtonActionPerformed
        try {
            // TODO add your handling code here:
            addPatientData();
        } catch (SQLException ex) {
            Logger.getLogger(PatientDataInsertForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_InsertButtonActionPerformed

     public void addPatientData() throws SQLException{
        
        PatientLogic myLogicLayer=new PatientLogic();
        myLogicLayer.setPatientDetails(name, familyName, age, gender, contactNo); 
    }
     
    private void Insert_textfield_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Insert_textfield_NameActionPerformed
        // TODO add your handling code here:
        name=evt.getActionCommand();
    }//GEN-LAST:event_Insert_textfield_NameActionPerformed

    private void View_Button_LoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_Button_LoadActionPerformed
        // TODO add your handling code here:
        loadPatientData();
    }//GEN-LAST:event_View_Button_LoadActionPerformed

    private void Diagnose_textfield_DoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Diagnose_textfield_DoseActionPerformed
        // TODO add your handling code here:
        quantityArray[arrayIndex]=(String)evt.getActionCommand()+" Tablets";
        System.out.println(quantityArray[arrayIndex]);
    }//GEN-LAST:event_Diagnose_textfield_DoseActionPerformed

    private void Diagnose_Button_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Diagnose_Button_OKActionPerformed
        try {
            // TODO add your handling code here:
            myLogicLayer.updatePatientDetails(name, history, medicineArray, quantityArray, sugarLevel, pressureLevel);
        } catch (SQLException ex) {
            Logger.getLogger(PatientDiagnoseForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Diagnose_Button_OKActionPerformed

    private void Diagnose_textfield_sugarLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Diagnose_textfield_sugarLevelActionPerformed
        // TODO add your handling code here:
        sugarLevel=Double.parseDouble(evt.getActionCommand());
        System.out.println(sugarLevel);
    }//GEN-LAST:event_Diagnose_textfield_sugarLevelActionPerformed

    private void Diagnose_textfield_pressureLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Diagnose_textfield_pressureLevelActionPerformed
        // TODO add your handling code here:
        pressureLevel=Double.parseDouble(evt.getActionCommand());
        System.out.println(pressureLevel);
    }//GEN-LAST:event_Diagnose_textfield_pressureLevelActionPerformed

    private void Diagnose_textfield_DoseperDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Diagnose_textfield_DoseperDayActionPerformed
        // TODO add your handling code here:
        quantityArray[arrayIndex]=(String)evt.getActionCommand()+" Bottels";
        System.out.println(quantityArray[arrayIndex]);
    }//GEN-LAST:event_Diagnose_textfield_DoseperDayActionPerformed

    private void Diagnose_Combobox_MedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Diagnose_Combobox_MedicineActionPerformed
        // TODO add your handling code here:
        medicineArray[arrayIndex]=(String)Diagnose_Combobox_Medicine.getSelectedItem();
        System.out.println(medicineArray[arrayIndex]);
    }//GEN-LAST:event_Diagnose_Combobox_MedicineActionPerformed

    private void Diagnose_Button_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Diagnose_Button_AddActionPerformed
        // TODO add your handling code here:
        Diagnose_List_Medicine.setListData(medicineArray);
        Diagnose_List_Quantity.setListData(quantityArray);
        Diagnose_textfield_Dose.setText(null);
        Diagnose_textfield_DoseperDay.setText(null);
        Diagnose_textfield_Days.setText(null);
        arrayIndex++;
    }//GEN-LAST:event_Diagnose_Button_AddActionPerformed

    private void Diagnose_textarea_RemarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Diagnose_textarea_RemarksActionPerformed
        // TODO add your handling code here:
        history=evt.getActionCommand();
        System.out.println(history);
    }//GEN-LAST:event_Diagnose_textarea_RemarksActionPerformed

    private void Diagnose_Combobox_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Diagnose_Combobox_NameActionPerformed

        name=(String)Diagnose_Combobox_Name.getSelectedItem();
        try {
            try {
                try {
                    try {
                        try {
                            // TODO add your handling code here:
                            Diagnose_Textarea_PreviousHistory.setText(myLogicLayer.getHistory(name));
                        } catch (SQLException ex) {
                            Logger.getLogger(PatientDiagnoseForm.class.getName()).log(Level.SEVERE, null, ex);
                        }

                        Diagnose_textarea_prescription.setText(myLogicLayer.getPrescription(name));
                    } catch (SQLException ex) {
                        Logger.getLogger(PatientDiagnoseForm.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    Diagnose_textarea_Remarks.setText(myLogicLayer.getHistory(name));
                } catch (SQLException ex) {
                    Logger.getLogger(PatientDiagnoseForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                Diagnose_textfield_sugarLevel.setText(myLogicLayer.getBloodSugarLevel(name));
            } catch (SQLException ex) {
                Logger.getLogger(PatientDiagnoseForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            Diagnose_textfield_pressureLevel.setText(myLogicLayer.getBloodPressureLevel(name));
        } catch (SQLException ex) {
            Logger.getLogger(PatientDiagnoseForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Diagnose_Combobox_NameActionPerformed

    private void Diagnose_List_MedicineValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_Diagnose_List_MedicineValueChanged
        // TODO add your handling code here:
        //jList1.setListData(listData);
    }//GEN-LAST:event_Diagnose_List_MedicineValueChanged

    private void Diagnose_textfield_DaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Diagnose_textfield_DaysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Diagnose_textfield_DaysActionPerformed

    private void Diagnose_textfield_VolumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Diagnose_textfield_VolumeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Diagnose_textfield_VolumeActionPerformed

     public void loadPatientData(){
        
        PatientLogic myLogicLayer=new PatientLogic();
      List<Patient> patientList=new ArrayList();
      DefaultTableModel patientDataTable=new DefaultTableModel();
      Object[ ] columnNames=new Object[6];
      Object[ ] fieldValues=new Object[6];
      Patient myPatient=null;
      
      try{
         patientList=myLogicLayer.getPatientDetails();
      }
      
      catch(SQLException e){
          System.out.println(e.getMessage());
      }
      
      columnNames[0]="Name";
      columnNames[1]="Age";
      columnNames[2]="ID";
      columnNames[3]="Gender";
      columnNames[4]="Family Name";
      columnNames[5]="Contact No.";
      
      patientDataTable.setColumnIdentifiers(columnNames);
      
      if(patientList.size()>0){
         
          for (Patient patientList1 : patientList) {
              myPatient = patientList1;
              fieldValues[0]=myPatient.getName().toString();
              fieldValues[1]=myPatient.getAge().toString();
              fieldValues[2]=myPatient.getID().toString();
              fieldValues[3]=myPatient.getGender().toString();
              fieldValues[4]=myPatient.getFamilyName().toString();
              fieldValues[5]=myPatient.getContactNo().toString();
              patientDataTable.addRow(fieldValues);
          }
          
          this.View_table.setModel(patientDataTable);
      }
      
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientOptionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientOptionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientOptionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientOptionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new PatientOptionForm().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(PatientOptionForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DiagnosePanel;
    private javax.swing.JButton Diagnose_Button_Add;
    private javax.swing.JButton Diagnose_Button_Cancel;
    private javax.swing.JButton Diagnose_Button_OK;
    private javax.swing.JComboBox Diagnose_Combobox_Medicine;
    private javax.swing.JComboBox Diagnose_Combobox_Name;
    private javax.swing.JList Diagnose_List_Medicine;
    private javax.swing.JList Diagnose_List_Quantity;
    private javax.swing.JTextArea Diagnose_Textarea_PreviousHistory;
    private javax.swing.JLabel Diagnose_lbl_Bottles;
    private javax.swing.JLabel Diagnose_lbl_Days;
    private javax.swing.JLabel Diagnose_lbl_Mdicine;
    private javax.swing.JLabel Diagnose_lbl_Name;
    private javax.swing.JLabel Diagnose_lbl_PatientHistory;
    private javax.swing.JLabel Diagnose_lbl_Prescription;
    private javax.swing.JLabel Diagnose_lbl_PressureLevel;
    private javax.swing.JLabel Diagnose_lbl_PreviousPrescription;
    private javax.swing.JLabel Diagnose_lbl_Quantity;
    private javax.swing.JLabel Diagnose_lbl_Remarks;
    private javax.swing.JLabel Diagnose_lbl_SelectMedicine;
    private javax.swing.JLabel Diagnose_lbl_SelectQuantity;
    private javax.swing.JLabel Diagnose_lbl_SugarLevel;
    private javax.swing.JLabel Diagnose_lbl_Tablets;
    private javax.swing.JTextField Diagnose_textarea_Remarks;
    private javax.swing.JTextArea Diagnose_textarea_prescription;
    private javax.swing.JTextField Diagnose_textfield_Days;
    private javax.swing.JTextField Diagnose_textfield_Dose;
    private javax.swing.JTextField Diagnose_textfield_DoseperDay;
    private javax.swing.JTextField Diagnose_textfield_Volume;
    private javax.swing.JTextField Diagnose_textfield_pressureLevel;
    private javax.swing.JTextField Diagnose_textfield_sugarLevel;
    private javax.swing.JPanel FamilyHistoryPanel;
    private javax.swing.JButton InsertButton;
    private javax.swing.JPanel InsertPanel;
    private javax.swing.JLabel Insert_lbl_Age;
    private javax.swing.JLabel Insert_lbl_ContactNo;
    private javax.swing.JLabel Insert_lbl_FamilyName;
    private javax.swing.JLabel Insert_lbl_Gender;
    private javax.swing.JLabel Insert_lbl_Name;
    private javax.swing.JRadioButton Insert_radioButton_female;
    private javax.swing.JRadioButton Insert_radioButton_male;
    private javax.swing.JTextField Insert_textfield_Age;
    private javax.swing.JTextField Insert_textfield_Name;
    private javax.swing.JTextField Insert_textfield_familyname;
    private javax.swing.JTextField Insert_textfield_gender;
    private javax.swing.JPanel PatientHistoryPanel;
    private javax.swing.JPanel ViewPanel;
    private javax.swing.JButton View_Button_Load;
    private javax.swing.JTable View_table;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
