/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View_Layer;

import Business_Logic_Layer.*;
import Data_Access_Layer.supplierDataAccessor;
import Data_Access_Layer.orderDataAccesor;
import Data_Access_Layer.chequeDataAccessor;
import Data_Access_Layer.bankDataAccessor;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import Business_Logic_Layer.Patient;
import Data_Access_Layer.PatientDataAccessor;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Ruchi
 */

public class supplierMain extends javax.swing.JFrame {
    
    supplier tempSupplier=null;
    order tempOrder=null;
    cheque tempCheque=null;
    bank tempBank;
    orderInfo newOrderInfoForm;
    private String name=null;
    private String contactDetails=null;
    private int phnNo=0;
    private String mail=null;
    private float orderAmountTotal=0;
    private String currentDate;
    String supplierName;
    String date;
    String itemName;
    String itemQuantity;
    float amount;
    
    private int chequeID;
    private String bankName;
    private float chequeAmount;
    private String inputDate;
        
    List<String> bankList=new ArrayList();
    List<String> supplierList=new ArrayList();
    List<Float> medicinePrice=new ArrayList();
    supplierDataAccessor dataAccessor=new supplierDataAccessor();
    orderDataAccesor orderDataAccessorObject=new orderDataAccesor();
    chequeDataAccessor chequeDataAccessObject=new chequeDataAccessor();
    bankDataAccessor newBankDataAccessor=new bankDataAccessor();
    chequeTableUpdate newChequeTable=new chequeTableUpdate();
    /**
     * Creates new form supplierMain
     */
    public supplierMain() {
        initComponents();
        order newOrder=new order();
        loadSupplier();
        newChequeTable.checkAndUpdate();
        this.loadCheques();
        this.loadBank();
        this.searchedPanel.setVisible(false);
        this.orderTable.setVisible(false);
        currentDate=newOrder.getCurrentDate();
        orderDateText.setText(newOrder.getCurrentDate());
        dateLabel.setText(newOrder.getCurrentDate());
        chequePayementDateText.setText(dateLabel.getText());
        
        
        try {
            // TODO add your handling code here:
            supplierList = dataAccessor.databaseInfo("Name");
            for(int i=0;i<supplierList.size();i++){
                orderNameCombo.addItem(supplierList.get(i));
                supplierDetailsOrderCombo.addItem(supplierList.get(i));
            }
        } catch (SQLException ex) {
            Logger.getLogger(supplierMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            // TODO add your handling code here:
            medicinePrice=dataAccessor.databaseMedicinePrices("Price");
            supplierList = dataAccessor.databaseMedicineInfo("Medicine_Name");
            for(int i=0;i<supplierList.size();i++){
                orderMedicineCombo.addItem(supplierList.get(i));
            }
        } catch (SQLException ex) {
            Logger.getLogger(supplierMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            // TODO add your handling code here:
            bankList=newBankDataAccessor.databaseInfo("bankName");
            
            for(int i=0;i<bankList.size();i++){
                bankSearchCombo.addItem(bankList.get(i));
                depositBankNameCombo.addItem(bankList.get(i));
            }
        } catch (SQLException ex) {
            Logger.getLogger(supplierMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //supplierTabbedPane.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paymentTypeCheck = new javax.swing.ButtonGroup();
        jButton3 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        contactLabel = new javax.swing.JLabel();
        contactText = new javax.swing.JTextField();
        phoneLabel = new javax.swing.JLabel();
        phoneText = new javax.swing.JTextField();
        mailText = new javax.swing.JTextField();
        mailLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        searchPanel = new javax.swing.JPanel();
        nameSearchLabel = new javax.swing.JLabel();
        nameSearchText = new javax.swing.JTextField();
        Searchbutton = new javax.swing.JButton();
        searchedPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        searchednameText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        searchedContactText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        searchPhnText = new javax.swing.JTextField();
        searchedMailText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        searchedAmountText = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        orderDateText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        orderQuantityText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        checkAmountButton = new javax.swing.JButton();
        addItemButton = new javax.swing.JButton();
        addOrderButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderTextPane = new javax.swing.JTextPane();
        orderMedicineCombo = new javax.swing.JComboBox();
        orderNameCombo = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        orderAmountLabel = new javax.swing.JLabel();
        orderSearchPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        orderSearchButton = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        orderIDdetailsText = new javax.swing.JTextField();
        supplierDetailsOrderCombo = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        paymenOrderIDText = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cashPaymentRadioButton = new javax.swing.JRadioButton();
        chequePayementRadioButton = new javax.swing.JRadioButton();
        chequePanel = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        chequePayementDateText = new javax.swing.JTextField();
        chequePaymentAmountText = new javax.swing.JTextField();
        chequePayementButton = new javax.swing.JButton();
        bankSearchCombo = new javax.swing.JComboBox();
        cashPaymentButton = new javax.swing.JButton();
        moneyIconLabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        bankTableUpdateButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        bankTable = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        depositBankNameCombo = new javax.swing.JComboBox();
        depositAmountText = new javax.swing.JTextField();
        bankDepositButton = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        chequeDetailTable = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        supplierjLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTabbedPane1.setOpaque(true);

        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        nameLabel.setText("Name");

        contactLabel.setText("Contact Details");

        contactText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactTextActionPerformed(evt);
            }
        });

        phoneLabel.setText("Tel. No");

        mailLabel.setText("E mail");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View_Layer/Truck-icon.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contactLabel)
                    .addComponent(nameLabel)
                    .addComponent(phoneLabel)
                    .addComponent(mailLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(nameText)
                        .addComponent(contactText)
                        .addComponent(phoneText)
                        .addComponent(mailText, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                    .addComponent(addButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 282, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactLabel)
                    .addComponent(contactText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneLabel)
                    .addComponent(phoneText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mailLabel)
                    .addComponent(mailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(addButton)
                .addContainerGap(170, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Add Supplier", jPanel1);

        nameSearchLabel.setText("Name");

        Searchbutton.setText("Search");
        Searchbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchbuttonActionPerformed(evt);
            }
        });

        jLabel2.setText("Name");

        searchednameText.setEditable(false);

        jLabel3.setText("Contact Details");

        searchedContactText.setEditable(false);

        jLabel4.setText("Phn No");

        searchPhnText.setEditable(false);

        searchedMailText.setEditable(false);

        jLabel5.setText("E-mail");

        jLabel6.setText("Amount");

        searchedAmountText.setEditable(false);

        javax.swing.GroupLayout searchedPanelLayout = new javax.swing.GroupLayout(searchedPanel);
        searchedPanel.setLayout(searchedPanelLayout);
        searchedPanelLayout.setHorizontalGroup(
            searchedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchedPanelLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(searchedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(searchedPanelLayout.createSequentialGroup()
                            .addGroup(searchedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6))
                            .addGap(30, 30, 30))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchedPanelLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(33, 33, 33)))
                    .addGroup(searchedPanelLayout.createSequentialGroup()
                        .addGroup(searchedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(50, 50, 50)
                        .addGroup(searchedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(searchPhnText, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(searchedContactText)
                            .addComponent(searchedMailText)
                            .addComponent(searchedAmountText)
                            .addComponent(searchednameText))))
                .addContainerGap(242, Short.MAX_VALUE))
        );
        searchedPanelLayout.setVerticalGroup(
            searchedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchedPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(searchedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(searchednameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(searchedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(searchedContactText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(searchedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(searchPhnText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(searchedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(searchedMailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(searchedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(searchedAmountText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addComponent(nameSearchLabel)
                        .addGap(26, 26, 26)
                        .addComponent(nameSearchText, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                        .addComponent(Searchbutton)
                        .addGap(76, 76, 76)))
                .addComponent(searchedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameSearchText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameSearchLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Searchbutton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addComponent(searchedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Search Supplier", searchPanel);

        jLabel7.setText("Supplier name");

        jLabel8.setText("Date");

        jLabel9.setText("Item ");

        jLabel10.setText("Quantity");

        jLabel11.setText("orderID");

        jLabel12.setText("Default");

        checkAmountButton.setText("Check Amount");
        checkAmountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAmountButtonActionPerformed(evt);
            }
        });

        addItemButton.setText("Add Item");
        addItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemButtonActionPerformed(evt);
            }
        });

        addOrderButton.setText("Add Order");
        addOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOrderButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(orderTextPane);

        orderNameCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderNameComboActionPerformed(evt);
            }
        });

        jLabel13.setText("Amount");

        orderAmountLabel.setText("0.0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(addOrderButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addItemButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkAmountButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(orderDateText)
                            .addComponent(orderQuantityText)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(orderMedicineCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(orderNameCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(orderAmountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(orderNameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(orderDateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(orderMedicineCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(orderQuantityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(orderAmountLabel))
                        .addGap(35, 35, 35)
                        .addComponent(checkAmountButton)
                        .addGap(18, 18, 18)
                        .addComponent(addItemButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addOrderButton)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Order Create", jPanel2);

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout orderSearchPanelLayout = new javax.swing.GroupLayout(orderSearchPanel);
        orderSearchPanel.setLayout(orderSearchPanelLayout);
        orderSearchPanelLayout.setHorizontalGroup(
            orderSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderSearchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButton1)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        orderSearchPanelLayout.setVerticalGroup(
            orderSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderSearchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(orderSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Supplier Details", orderSearchPanel);

        jLabel14.setText("Supplier Name");

        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "OrderID", "Supplier Name", "Order Date", "Order Info", "Order amount"
            }
        ));
        jScrollPane3.setViewportView(orderTable);

        orderSearchButton.setText("Search");
        orderSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderSearchButtonActionPerformed(evt);
            }
        });

        jLabel15.setText("Order ID");

        orderIDdetailsText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderIDdetailsTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(orderIDdetailsText, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(supplierDetailsOrderCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(orderSearchButton)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(orderSearchButton)
                    .addComponent(supplierDetailsOrderCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(orderIDdetailsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        jTabbedPane1.addTab("Order details", jPanel3);

        jButton2.setText("Testing");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel16.setText("Order ID");

        jLabel17.setText("Select the payment type");

        paymentTypeCheck.add(cashPaymentRadioButton);
        cashPaymentRadioButton.setText("Cash");
        cashPaymentRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashPaymentRadioButtonActionPerformed(evt);
            }
        });

        paymentTypeCheck.add(chequePayementRadioButton);
        chequePayementRadioButton.setText("Cheque");
        chequePayementRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chequePayementRadioButtonActionPerformed(evt);
            }
        });

        jLabel18.setText("Cheque Payements Only");

        jLabel19.setText("Bank");

        jLabel20.setText("Cheque Date");

        jLabel21.setText("Cheque Amount");

        chequePayementButton.setText("Cheque Payment");
        chequePayementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chequePayementButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout chequePanelLayout = new javax.swing.GroupLayout(chequePanel);
        chequePanel.setLayout(chequePanelLayout);
        chequePanelLayout.setHorizontalGroup(
            chequePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chequePanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(chequePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(chequePanelLayout.createSequentialGroup()
                        .addGroup(chequePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(chequePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chequePayementButton, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(chequePaymentAmountText)
                            .addComponent(chequePayementDateText)
                            .addComponent(bankSearchCombo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39))
                    .addGroup(chequePanelLayout.createSequentialGroup()
                        .addGroup(chequePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        chequePanelLayout.setVerticalGroup(
            chequePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chequePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(chequePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(bankSearchCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(chequePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(chequePayementDateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(chequePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(chequePaymentAmountText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(chequePayementButton)
                .addContainerGap())
        );

        cashPaymentButton.setText("Cash Payment");
        cashPaymentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashPaymentButtonActionPerformed(evt);
            }
        });

        moneyIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View_Layer/money_icon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(paymenOrderIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 433, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(moneyIconLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cashPaymentRadioButton)
                            .addComponent(chequePayementRadioButton))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(chequePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(cashPaymentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(paymenOrderIDText)
                        .addComponent(jButton2)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(moneyIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cashPaymentRadioButton)
                .addGap(18, 18, 18)
                .addComponent(chequePayementRadioButton)
                .addGap(18, 18, 18)
                .addComponent(chequePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cashPaymentButton)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Received Order", jPanel4);

        jPanel5.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));

        bankTableUpdateButton.setText("Update");
        bankTableUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankTableUpdateButtonActionPerformed(evt);
            }
        });

        bankTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(bankTable);

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel22.setText("Bank Name");

        jLabel23.setText("Amount");

        bankDepositButton.setText("Deposit");
        bankDepositButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankDepositButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bankDepositButton)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(depositBankNameCombo, 0, 128, Short.MAX_VALUE)
                            .addComponent(depositAmountText))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(depositBankNameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(depositAmountText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bankDepositButton)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View_Layer/bank.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(bankTableUpdateButton))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel25)))
                .addGap(28, 28, 28))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bankTableUpdateButton)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );

        jTabbedPane1.addTab("Bank Details", jPanel5);

        chequeDetailTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(chequeDetailTable);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View_Layer/1414370520_application-vnd.ms-excel.png"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addGap(33, 33, 33))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(205, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cheque Details", jPanel7);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(28, 57, 813, 470);

        supplierjLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        supplierjLabel.setForeground(new java.awt.Color(255, 255, 255));
        supplierjLabel.setText("Supplier Management");
        getContentPane().add(supplierjLabel);
        supplierjLabel.setBounds(361, 16, 203, 35);
        getContentPane().add(dateLabel);
        dateLabel.setBounds(778, 11, 118, 0);

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View_Layer/blurry_blue_background.jpg"))); // NOI18N
        getContentPane().add(jLabel24);
        jLabel24.setBounds(0, 0, 1020, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contactTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactTextActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        try{
        name=nameText.getText();
        contactDetails=contactText.getText();
        phnNo=Integer.parseInt(phoneText.getText());
        mail=mailText.getText();
        }
        catch(Exception e){
            
        }
        
        tempSupplier=new supplier(name, contactDetails, phnNo, mail);
        
        
        try {
            //dataAccessor.retrievePatientData();
            dataAccessor.insertSupplierData(tempSupplier);
            
            
        } catch (SQLException ex) {
            Logger.getLogger(supplierMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void SearchbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchbuttonActionPerformed
        // TODO add your handling code here:
        this.searchedPanel.setVisible(true);
        ResultSet dataset;
        
        try {
            
            tempSupplier = dataAccessor.browseSupplier(nameSearchText.getText());
            
            searchednameText.setText(tempSupplier.getName());
            searchedContactText.setText(tempSupplier.getContactDetails());
            searchPhnText.setText(Integer.toString(tempSupplier.getPhnNo()));
            searchedMailText.setText(tempSupplier.getMail());
            searchedAmountText.setText(""+tempSupplier.getAmount());
            
        } catch (SQLException ex) {
            Logger.getLogger(supplierMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_SearchbuttonActionPerformed

    private void orderNameComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderNameComboActionPerformed
        
        
    }//GEN-LAST:event_orderNameComboActionPerformed

    private void addItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemButtonActionPerformed
        // TODO add your handling code here:
        order newOrder=new order();
        String old=orderTextPane.getText();
        
        try{
        newOrder.getCurrentDate();
        supplierName=orderNameCombo.getSelectedItem().toString();
        date=orderDateText.getText();
        itemName=orderMedicineCombo.getSelectedItem().toString();
        itemQuantity=orderQuantityText.getText();
        float price=medicinePrice.get(orderMedicineCombo.getSelectedIndex());
        amount=price*Integer.parseInt(itemQuantity);
        String finalAmount= String.valueOf(amount);
        orderAmountLabel.setText(finalAmount);
        
        orderTextPane.setText(old+newOrder.createOrderString(supplierName, date, itemName, itemQuantity,finalAmount)+"\n");
        orderAmountTotal=orderAmountTotal+amount;
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Incorrect item input ","Error",JOptionPane.WARNING_MESSAGE);
        }
        
        
        //System.out.println(newOrder.createOrderString(supplierName, date, itemName, itemQuantity, amount));
    }//GEN-LAST:event_addItemButtonActionPerformed

    private void checkAmountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAmountButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Your Total amount is "+orderAmountTotal,"Total Order Amount",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_checkAmountButtonActionPerformed

    private void addOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOrderButtonActionPerformed
        // TODO add your handling code here:
        orderTextPane.setText(orderTextPane.getText()+"\n"+"Total Amount      "+orderAmountTotal);
        order newOrder=new order(supplierName,date,orderTextPane.getText(),orderAmountTotal);
        try {
            orderDataAccessorObject.insertSupplierData(newOrder);
        } catch (SQLException ex) {
            Logger.getLogger(supplierMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addOrderButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.loadSupplier();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void orderSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderSearchButtonActionPerformed
        // TODO add your handling code here:
        this.loadOrder();
    }//GEN-LAST:event_orderSearchButtonActionPerformed

    private void orderIDdetailsTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderIDdetailsTextActionPerformed
        try {
            // TODO add your handling code here:
            String temp=(orderDataAccessorObject.retrieveOrderInfo(supplierDetailsOrderCombo.getSelectedItem().toString(),Integer.parseInt(orderIDdetailsText.getText())));
            newOrderInfoForm=new orderInfo(temp);
            newOrderInfoForm.setVisible(true);
            
        } catch (SQLException ex) {
            Logger.getLogger(supplierMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_orderIDdetailsTextActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        cheque newCheque=new cheque(1,"BOC", name, amount);
        newCheque.dateSplit("2014/04/15 ");
        supplierDataAccessor dataAccessObject=new supplierDataAccessor();
        try {
            amount=dataAccessObject.retrieveSupplierAmount("Glaxo");
            System.out.println("" + amount);
        } catch (SQLException ex) {
            Logger.getLogger(supplierMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void chequePayementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chequePayementButtonActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            orderDataAccessorObject.deleteOrderInfo(Integer.parseInt(paymenOrderIDText.getText()));
        } catch (SQLException ex) {
            Logger.getLogger(supplierMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try{
            this.bankName=bankSearchCombo.getSelectedItem().toString();
            this.inputDate=chequePayementDateText.getText();
            this.chequeAmount=Float.parseFloat(chequePaymentAmountText.getText());
        
        
            tempCheque=new cheque(bankName, inputDate, chequeAmount);
        
            if(tempCheque.chequeDateCheck(currentDate)){
                chequeDataAccessObject.insertChequeData(tempCheque);
            }
            else{
                JOptionPane.showMessageDialog(null,"Incorrect cheque date ","Error",JOptionPane.WARNING_MESSAGE);
            }
                
        }
        catch (SQLException ex) {
            Logger.getLogger(supplierMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Incorrect item input ","Error",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_chequePayementButtonActionPerformed

    private void chequePayementRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chequePayementRadioButtonActionPerformed
        // TODO add your handling code here:
        chequePanel.setVisible(true);
    }//GEN-LAST:event_chequePayementRadioButtonActionPerformed

    private void cashPaymentRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashPaymentRadioButtonActionPerformed
        // TODO add your handling code here:
        chequePanel.setVisible(false);
    }//GEN-LAST:event_cashPaymentRadioButtonActionPerformed

    private void cashPaymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashPaymentButtonActionPerformed
        try {
            // TODO add your handling code here:
            orderDataAccessorObject.deleteOrderInfo(Integer.parseInt(paymenOrderIDText.getText()));
        } catch (SQLException ex) {
            Logger.getLogger(supplierMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cashPaymentButtonActionPerformed

    private void bankTableUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bankTableUpdateButtonActionPerformed
        
        this.loadBank();
        try {
            // TODO add your handling code here:
            newBankDataAccessor.RetrieveBankAccountBalance("Bank of Ceylon");
        } catch (SQLException ex) {
            Logger.getLogger(supplierMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bankTableUpdateButtonActionPerformed

    private void bankDepositButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bankDepositButtonActionPerformed
        try {
            // TODO add your handling code here:
            float tempAmount=0;
            tempAmount=newBankDataAccessor.RetrieveBankAccountBalance(this.depositBankNameCombo.getSelectedItem().toString());
            newBankDataAccessor.updateBankAmount(this.depositBankNameCombo.getSelectedItem().toString(),tempAmount+Float.parseFloat(this.depositAmountText.getText()));
            this.bankTableUpdateButton.doClick();
        } catch (SQLException ex) {
            Logger.getLogger(supplierMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bankDepositButtonActionPerformed
    
    
    
    public void loadSupplier(){
        
      supplierDataAccessor dataAccessObject=new supplierDataAccessor();
      List<supplier> supList=new ArrayList();
      DefaultTableModel patientDataTable=new DefaultTableModel();
      
      Object[ ] columnNames=new Object[5];
      Object[ ] fieldValues=new Object[5];
      Patient myPatient=null;
      
      try{
         supList=dataAccessObject.retrieveSupplierData();
      }
      
      catch(SQLException e){
          System.out.println(e.getMessage());
      }
      
      columnNames[0]="Name";
      columnNames[1]="ContactDetails";
      columnNames[2]="PhnNo";
      columnNames[3]="E-mail";
      columnNames[4]="Amount";
      
      
      patientDataTable.setColumnIdentifiers(columnNames);
      
      if(supList.size()>0){
         
          for (supplier patientList1 : supList) {
              tempSupplier = patientList1;
              fieldValues[0]=tempSupplier.getName();
              fieldValues[1]=tempSupplier.getContactDetails();
              fieldValues[2]=tempSupplier.getPhnNo();
              fieldValues[3]=tempSupplier.getMail();
              fieldValues[4]=tempSupplier.getAmount();
              
              patientDataTable.addRow(fieldValues);
          }
          
          this.jTable1.setModel(patientDataTable);
      }
    }
    
    
    public void loadOrder(){
        
      orderDataAccesor dataAccessOrder=new orderDataAccesor();
      
      List<order> orderList=new ArrayList();
      DefaultTableModel orderDataTable=new DefaultTableModel();
      
      Object[ ] columnNames=new Object[5];
      Object[ ] fieldValues=new Object[5];
      //Patient myPatient=null;
      
      try{
         orderList=dataAccessOrder.retrieveOrderData(supplierDetailsOrderCombo.getSelectedItem().toString());
      }
      
      catch(SQLException e){
          System.out.println(e.getMessage());
      }
      
      if(orderList.isEmpty()){
          JOptionPane.showMessageDialog(null,"No orders from the selected supplier ","Information",JOptionPane.WARNING_MESSAGE);
      }
      
      
      columnNames[0]="OrderID";
      columnNames[1]="Supplier Name";
      columnNames[2]="Order Date";
      columnNames[3]="Order Info";
      columnNames[4]="Order Amount";
      
      
      orderDataTable.setColumnIdentifiers(columnNames);
      
      if(orderList.size()>0){
         
          for (order newOrder : orderList) {
              tempOrder = newOrder;
              fieldValues[0]=tempOrder.getOrderID();
              fieldValues[1]=tempOrder.getSupplierName();
              fieldValues[2]=tempOrder.getOrderDate();
              fieldValues[3]=tempOrder.getOrderInfo();
              fieldValues[4]=tempOrder.getOrderAmount();
              
              orderDataTable.addRow(fieldValues);
          }
          
          this.orderTable.setModel(orderDataTable);
          this.orderTable.setVisible(true);
      }
    }
     
    public void loadBank(){
        
      orderDataAccesor dataAccessOrder=new orderDataAccesor();
      
      List<bank> bankList=new ArrayList();
      DefaultTableModel orderDataTable=new DefaultTableModel();
      
      Object[ ] columnNames=new Object[4];
      Object[ ] fieldValues=new Object[4];
      //Patient myPatient=null;
      
      try{
         bankList=newBankDataAccessor.retriveBankinfo();
      }
      
      catch(SQLException e){
          System.out.println(e.getMessage());
      }
      
      if(bankList.isEmpty()){
          JOptionPane.showMessageDialog(null,"No orders from the selected supplier ","Information",JOptionPane.WARNING_MESSAGE);
      }
      
      
      columnNames[0]="Bank ID";
      columnNames[1]="Bank Name";
      columnNames[2]="Acount No";
      columnNames[3]="Account Balance";
     
      
      
      orderDataTable.setColumnIdentifiers(columnNames);
      
      if(bankList.size()>0){
         
          for (bank newBank : bankList) {
              tempBank = newBank;
              fieldValues[0]=tempBank.getBankID();
              fieldValues[1]=tempBank.getBankName();
              fieldValues[2]=tempBank.getAccNo();
              fieldValues[3]=tempBank.getAccBalance();
              
              orderDataTable.addRow(fieldValues);
          }
          
          this.bankTable.setModel(orderDataTable);
          this.bankTable.setVisible(true);
      }
    }
    
    public void loadCheques(){
        
      chequeDataAccessor dataAccessorCheque=new chequeDataAccessor();
      
      List<cheque> chequeList=new ArrayList();
      DefaultTableModel orderDataTable=new DefaultTableModel();
      
      Object[ ] columnNames=new Object[4];
      Object[ ] fieldValues=new Object[4];
      //Patient myPatient=null;
      
      try{
         chequeList=dataAccessorCheque.retriveChequeinfo();
      }
      
      catch(SQLException e){
          System.out.println(e.getMessage());
      }
      
      if(chequeList.isEmpty()){
          JOptionPane.showMessageDialog(null,"No cheques ","Information",JOptionPane.WARNING_MESSAGE);
      }
      
      
      columnNames[0]="Cheque ID";
      columnNames[1]="Bank Name";
      columnNames[2]="Cheque Date";
      columnNames[3]="Cheque Amount";
     
      
      
      orderDataTable.setColumnIdentifiers(columnNames);
      
      if(chequeList.size()>0){
         
          for (cheque newCheque : chequeList) {
              tempCheque = newCheque;
              fieldValues[0]=tempCheque.getChequeID();
              fieldValues[1]=tempCheque.getBankName();
              fieldValues[2]=tempCheque.getInputDate();
              fieldValues[3]=tempCheque.getChequeAmount();
              
              orderDataTable.addRow(fieldValues);
          }
          
          this.chequeDetailTable.setModel(orderDataTable);
          
      }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            System.out.println(ex);
            java.util.logging.Logger.getLogger(supplierMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            System.out.println("Error");
            java.util.logging.Logger.getLogger(supplierMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            System.out.println("Error");
            java.util.logging.Logger.getLogger(supplierMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            System.out.println("Error");
            java.util.logging.Logger.getLogger(supplierMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new supplierMain().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Searchbutton;
    private javax.swing.JButton addButton;
    private javax.swing.JButton addItemButton;
    private javax.swing.JButton addOrderButton;
    private javax.swing.JButton bankDepositButton;
    private javax.swing.JComboBox bankSearchCombo;
    private javax.swing.JTable bankTable;
    private javax.swing.JButton bankTableUpdateButton;
    private javax.swing.JButton cashPaymentButton;
    private javax.swing.JRadioButton cashPaymentRadioButton;
    private javax.swing.JButton checkAmountButton;
    private javax.swing.JTable chequeDetailTable;
    private javax.swing.JPanel chequePanel;
    private javax.swing.JButton chequePayementButton;
    private javax.swing.JTextField chequePayementDateText;
    private javax.swing.JRadioButton chequePayementRadioButton;
    private javax.swing.JTextField chequePaymentAmountText;
    private javax.swing.JLabel contactLabel;
    private javax.swing.JTextField contactText;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JTextField depositAmountText;
    private javax.swing.JComboBox depositBankNameCombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel mailLabel;
    private javax.swing.JTextField mailText;
    private javax.swing.JLabel moneyIconLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameSearchLabel;
    private javax.swing.JTextField nameSearchText;
    private javax.swing.JTextField nameText;
    private javax.swing.JLabel orderAmountLabel;
    private javax.swing.JTextField orderDateText;
    private javax.swing.JTextField orderIDdetailsText;
    private javax.swing.JComboBox orderMedicineCombo;
    private javax.swing.JComboBox orderNameCombo;
    private javax.swing.JTextField orderQuantityText;
    private javax.swing.JButton orderSearchButton;
    private javax.swing.JPanel orderSearchPanel;
    private javax.swing.JTable orderTable;
    private javax.swing.JTextPane orderTextPane;
    private javax.swing.JTextField paymenOrderIDText;
    private javax.swing.ButtonGroup paymentTypeCheck;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JTextField phoneText;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JTextField searchPhnText;
    private javax.swing.JTextField searchedAmountText;
    private javax.swing.JTextField searchedContactText;
    private javax.swing.JTextField searchedMailText;
    private javax.swing.JPanel searchedPanel;
    private javax.swing.JTextField searchednameText;
    private javax.swing.JComboBox supplierDetailsOrderCombo;
    private javax.swing.JLabel supplierjLabel;
    // End of variables declaration//GEN-END:variables
}
